#trigger:
#  - main

pool: slave

variables:
  COMPONENT: 'user'


resources:
  repositories:
    - repository: templates
      type: github
      name: GurukaYadav/roboshop-azure-devops-templates
      endpoint: GurukaYadav

stages:
  - template: nodejs.yml@templates